// <auto-generated />
using System;
using System.Collections.Generic;
using Inventory.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inventory.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260308005124_ProductsToDB")]
    partial class ProductsToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inventory.Domain.MeasurementUnits.MeasurementUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.ComplexProperty(typeof(Dictionary<string, object>), "MeasurementUnitAbbreviation", "Inventory.Domain.MeasurementUnits.MeasurementUnit.MeasurementUnitAbbreviation#MeasurementUnitAbbreviation", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("abbreviation");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "MeasurementUnitName", "Inventory.Domain.MeasurementUnits.MeasurementUnit.MeasurementUnitName#MeasurementUnitName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("name");
                        });

                    b.HasKey("Id");

                    b.ToTable("measurement_units", "inventory");
                });

            modelBuilder.Entity("Inventory.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasColumnOrder(2);

                    b.Property<decimal>("MinStock")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("min_stock")
                        .HasColumnOrder(9);

                    b.ComplexProperty(typeof(Dictionary<string, object>), "BarCode", "Inventory.Domain.Products.Product.BarCode#BarCode", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("character varying(14)")
                                .HasColumnName("bar_code")
                                .HasColumnOrder(1);
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Cost", "Inventory.Domain.Products.Product.Cost#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("cost_amount")
                                .HasColumnOrder(3);

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency")
                                .HasColumnOrder(4);
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "Inventory.Domain.Products.Product.Price#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("price_amount")
                                .HasColumnOrder(5);
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Stock", "Inventory.Domain.Products.Product.Stock#Stock", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("stock")
                                .HasColumnOrder(8);
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "WholesalePrice", "Inventory.Domain.Products.Product.WholesalePrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("wholesale_price_amount")
                                .HasColumnOrder(7);
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "WholesaleQuantity", "Inventory.Domain.Products.Product.WholesaleQuantity#Quantity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("wholesale_quantity")
                                .HasColumnOrder(6);
                        });

                    b.HasKey("Id");

                    b.ToTable("products", "inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
