// <auto-generated />
using System;
using System.Collections.Generic;
using Inventory.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inventory.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260226043745_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inventory.Domain.MeasurementUnits.MeasurementUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.ComplexProperty(typeof(Dictionary<string, object>), "MeasurementUnitAbbreviation", "Inventory.Domain.MeasurementUnits.MeasurementUnit.MeasurementUnitAbbreviation#MeasurementUnitAbbreviation", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Abbreviation");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "MeasurementUnitName", "Inventory.Domain.MeasurementUnits.MeasurementUnit.MeasurementUnitName#MeasurementUnitName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Name");
                        });

                    b.HasKey("Id");

                    b.ToTable("MeasurementUnit");
                });
#pragma warning restore 612, 618
        }
    }
}
